//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptingMod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptingMod.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area is too far away, chunk(s) not loaded. Move closer!.
        /// </summary>
        internal static string ErrorAreaTooFarAway {
            get {
                return ResourceManager.GetString("ErrorAreaTooFarAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk cache not yet ready..
        /// </summary>
        internal static string ErrorChunkCacheNotReady {
            get {
                return ResourceManager.GetString("ErrorChunkCacheNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the given coordinates is not a valid integer..
        /// </summary>
        internal static string ErrorCoordinateNotInteger {
            get {
                return ResourceManager.GetString("ErrorCoordinateNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during command execution: {0} [details in server log].
        /// </summary>
        internal static string ErrorDuringCommand {
            get {
                return ResourceManager.GetString("ErrorDuringCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get your remote client info. You must be logged in as a regular player..
        /// </summary>
        internal static string ErrorNotRemotePlayer {
            get {
                return ResourceManager.GetString("ErrorNotRemotePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter count not valid. See help for details..
        /// </summary>
        internal static string ErrorParameerCountNotValid {
            get {
                return ResourceManager.GetString("ErrorParameerCountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World not yet ready..
        /// </summary>
        internal static string ErrorWorldNotReady {
            get {
                return ResourceManager.GetString("ErrorWorldNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk regeneration in walk mode turned off..
        /// </summary>
        internal static string MsgRegenerationWalkOff {
            get {
                return ResourceManager.GetString("MsgRegenerationWalkOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk regeneration in walk mode turned on..
        /// </summary>
        internal static string MsgRegenerationWalkOn {
            get {
                return ResourceManager.GetString("MsgRegenerationWalkOn", resourceCulture);
            }
        }
    }
}
